if(EXISTS "C:/Users/HeoCop/Downloads/Projects/UnikeyTSF/build64/IPCTests[1]_tests.cmake")
  include("C:/Users/HeoCop/Downloads/Projects/UnikeyTSF/build64/IPCTests[1]_tests.cmake")
else()
  add_test(IPCTests_NOT_BUILT IPCTests_NOT_BUILT)
endif()
